# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	
	config.vm.box = "bento/ubuntu-20.04"
	config.ssh.insert_key = false
	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.provider :virtualbox do |v|
		v.memory = 512
		v.linked_clone = true
	end
	
	config.vm.define "master" do |master|
		master.vm.hostname = "master"
		master.vm.network :private_network, ip: "192.168.69.69"
	end
	
	config.vm.define "worker1" do |worker1|
		worker1.vm.hostname = "worker1"
		worker1.vm.network :private_network, ip: "192.168.69.70"
	end

	config.vm.define "worker2" do |worker2|
		worker2.vm.hostname = "worker2"
		worker2.vm.network :private_network, ip: "192.168.69.71"
	end
end
