---
# tasks file for k8s-setup
- name: Ensure /etc/hosts is provided and consistent.
  copy:
    src: "../files/hosts"
    dest: /etc/hosts
  become: yes

- name: Setting up kernel modules for containerd.
  lineinfile:
     - path: /etc/modules-load.d/containerd.conf
       regexp: '^overlay'
       line: 'overlay'
     - path: /etc/modules-load.d/containerd.conf
       regexp: '^br_netfilter'
       line: 'br_netfilter'
